### ISSUE TITLE
Having trouble verifying results

### ISSUE THREAD

**Issue by tleyden** [Atif-Anwer/Mediapipe_to_OpenPose_JSON#2]
Great idea for a tool!  Mediapipe is much easier to install than OpenPose.

I tried to verify the results using [this code snippet](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1644#issuecomment-657361528), but the output doesn't look as expected.

The mediapipe output is: 
 
![pose_wireframe](https://github.com/Atif-Anwer/Mediapipe_to_OpenPose_JSON/assets/296876/9e9f4417-0fa7-4ce9-80bf-5e837f312a30)

(this was generated using the code snippet on [this blog post](https://www.assemblyai.com/blog/mediapipe-for-dummies/))

But when I try to instead use this repo to generate the mediapipe keypoints and convert them to OpenPose, and then use [this code snippet](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1644#issuecomment-657361528) to visualize, it shows this:

![people_snapshot_pose_keypoints json_skel](https://github.com/Atif-Anwer/Mediapipe_to_OpenPose_JSON/assets/296876/2d39ae61-1053-4cec-8dd2-ffe3832aca32)

Does this look like a bug in the conversion to OpenPose or a bug in the visualization?  Or do you know another easy way to visualize OpenPose keypoints?  (ideally superimposed with the image)

**Comment by Atif-Anwer** [comment]
Thanks for pointing that out and pushing me to add an openpose skeleton generator also :D . There was a silly mistake again from my end that ive fixed now. Also i've added the fixed code (there was a mistake in that also!) from the reference above that can be used to generate the skeletons to verify that its working corectly. 

Ive also added ground truth JSON files that ive generated from the OpenPose windows binary to compare the generated JSON files. Please update / re-download the updated commit!

**Comment by Atif-Anwer** [comment]
@tleyden Can you confirm if its working for you now 🤞🏼  ?

**Comment by tleyden** [comment]
I tried again, it's definitely improved, but there is still an unexpected line in the visualization.  Any idea why that might be happening?

![people_snapshot_pose_keypoints json_skel markup](https://github.com/Atif-Anwer/Mediapipe_to_OpenPose_JSON/assets/296876/b2146d63-87bb-4e5f-8131-921905d783fb)

**Comment by Atif-Anwer** [comment]
> I tried again, it's definitely improved, but there is still an unexpected line in the visualization. Any idea why that might be happening?
> 


I believe you are using the original script. There was an error in that also, and ive fixed that too. The updated script is in my repo now with the latest commit. It would remove this artifact if you try it now. 
I also posted the correction over at the original thread by the author (https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1644#issuecomment-1562861033)

**Comment by tleyden** [comment]
Yes I was using the original script to render the openpose visualization.  I will try the updated script, thanks!
