### ISSUE TITLE
Hands an Faces Keypoints Need

### ISSUE THREAD

**Issue by imfurkaann** [Atif-Anwer/Mediapipe_to_OpenPose_JSON#3]
Thank you for writing such code. In the code, I want to add the hands and faces to the json file, but I couldn't, can you help?

**Comment by Atif-Anwer** [comment]
Well, It can be done easily i think. Once youve got the hand+face keypoints from  Mediapipe, you can simply convert them to a list (as ive done in the code).
Then in the mediapipe_JSON.py file, you can simply add the variables in lines 177-179 
```
"face_keypoints_3d"      : [],
"hand_left_keypoints_3d" : [],
"hand_right_keypoints_3d": []
```

But note that the JSON will not be compatible with the OpenPose format. So Its not really what I wanted to achieve.
